### ISSUE TITLE
PracticeElement1 is at 1.90 but actual perfect alignment is 1.85

### ISSUE THREAD

**Issue by ucddj** [iguanacore/iguana_acs_functions#17]
The +15 Moodlet "Perfect Alignment of the Five Elements" displays at 1.90 element ~~composition~~ strength but the cultivation / golden core breakthrough are optimal both at 1.85. 

While this has never been an issue so far, lowering the requirement for the moodlet to 1.85 for homogeneity could help a player experimenting on their own to find the optimal composition by themselves.

In case a tool is developed in the future to recommend cultivation rooms, it will also allow players to verify the element ~~composition~~ strength by themselves by checking the moodlets..

**Comment by iguanacore** [comment]
Element strength, not composition.
But yes, that does make sense. Enough to be a potential fix related change. But since the line is thin and wavy, this works as well.
Changing the `PracticeElement2MoonNameMap` dictionary shouldn't be a major change.
