### ISSUE TITLE
Agencies pop increase does not work correctly

### ISSUE THREAD

**Issue by ucddj** [iguanacore/iguana_acs_functions#29]
Explained here: https://discord.com/channels/608499065071861761/608499065071861764/1138662001002938438 (and next messages)

My hypothesis is that the issue comes from `GetRegionPopulationAddPerday` returning a `NaN` when population raises above 400,000, as the `Math.Sqrt` call receives a negative value parameter (https://learn.microsoft.com/fr-fr/dotnet/api/system.math.sqrt?view=net-7.0).

As a consequence, the `Clamp` in `AddPopulation` resets back agency pop at 50,000.

Would need to be tested to be sure however.

**Comment by iguanacore** [comment]
Let's see what a dirty solution to it would look like. For starters, a Transpiler for the function mentioned, turning 40K into 99999, keeping in line with the 1/10 of the "capped" value.
