### ISSUE TITLE
Wudang Duck not appearing

### ISSUE THREAD

**Issue by DitDoo** [iguanacore/iguana_acs_functions#38]
The wudang duck doesnt appear in any of the wudang locations with this mod enabled, as he does with iguana_WudangTranslation. 
I'm not sure if the intended behaviour is to have him always appear as he does with iguana_WudangTranslation, so not sure if bug.

**Comment by iguanacore** [comment]
Some steps for verification/clarification.

The following tests can be done with ModModifier on my end, but the same could technically be accomplished with the console and a basic script.

- [ ] With ModModifier, under Traders, and clicking on All NPCs button, does WudangDuck show up? 
- [ ] If yes, is the CNOnly parameter properly set to 0?
- [ ] If it is, can the Duck be found on any other Wudang locations apart from the main one?

Testing with the current repo contents shows on my end that the CNOnly parameter is **not** set to 0, meaning that the Jianghu NPC isn't properly overwritten. When comparing repo contents to the iguana_WudangTranslation mod, the reason for that should be obvious. A quick fix all things considered.
