### ISSUE TITLE
Display Base Mental State UI bug

### ISSUE THREAD

**Issue by iguanacore** [iguanacore/iguana_acs_functions#45]
ModLoaderLite settings related, when the save file is corrupted or missing, selecting someone who has Mental State (like Xiandao), the UI bugs out.

One way to replicate the issue:
* Delete the .MLL file for the save
* Load that save file
* Select a Cultivator
* Issue appears

Another way of replicating the issue:
* Start a new run
* Save the game, use a new and unique name for the save file
* Load that file
* Select a Cultivator
* Issue appears

After the issue appears, it can be solved by rewriting the save file (which creates a new and working .MLL file for the save) and loading the rewritten file.
One possible solution could be making the aspect disabled by default, and requiring the player to enable it.

**Comment by NecrCode** [comment]
it works fine for as long as i don't select a cultivator, no matter how many times i reload the save:
- Load the save
- Select a Cultivator (works fine)
- Reload the save
- Select a Cultivator
- Issue appears

and if you comment this `currentMentalStateSlider.AddChild( baseMentalStateBar );` Line:58, then the issue no longer appears.

**Comment by iguanacore** [comment]
Resolved with #48
